#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  GithubUsername: johnnyreilly
  GithubPassword:
    secure: ilM6UXjXXOmFLz6pDWsoOA==
  testVariable:
    secure: JnsTiFLXDTQVPQVUjQDWSg==
    
branches:
  only:
    - master

install:
- ps: choco install wget

build:
  verbosity: minimal

# 

after_test:
- ps: git remote -v
- ps: ./makeStatic.ps1 $env:APPVEYOR_BUILD_FOLDER
- ps: git config --global user.email "johnny_reilly@hotmail.com"
- ps: git config --global user.name "johnnyreilly"
- ps: git config --global push.default matching
- ps: cd "$($env:APPVEYOR_BUILD_FOLDER)\..\"
- ps: ls
- ps: mkdir gh-pages
- ps: git clone --quiet --branch=gh-pages https://$($env:GithubUsername):$($env:GithubPassword)@github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native.git .\gh-pages\
- ps: cd gh-pages
- ps: git status
- ps: ls
- ps: Get-ChildItem -Attributes !r | Remove-Item -Recurse -Force
- ps: ls
- ps: copy-item -path ..\static-site\* -Destination $pwd.Path -Recurse
- ps: ls
- ps: git status
#- ps: git status | grep "up to date"
#- ps: git commit -a -m "skip ci - static site regeneration"
#- ps: git status --porcelain
#- ps: git push
#- ps: git push ..\push.log 2<&1
#- ps: cat ..\push.log

#- ps: git remote set-url origin 'https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native.git'
#- ps: git remote -v
#- ps: Get-ChildItem -Attributes !r | Remove-Item -Recurse -Force
#- ps: copy-item -path ..\static-site\* -Destination $env:APPVEYOR_BUILD_FOLDER -Recurse
#- ps: git commit -a -m "skip ci - static site regeneration"

