#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

install:
- ps: choco install wget

build:
  verbosity: minimal

after_build:
  - ps: $jVUNDemo = "$($env:APPVEYOR_BUILD_FOLDER)\jVUNDemo"
  - ps: $staticSite = "$jVUNDemo\..\..\"
  - ps: write-host "jVUNDemo location: $jVUNDemo"
  - ps: write-host "static site location: $staticSite"
  - ps: ls C:\Program Files (x86)\IIS Express\
  - ps: write-host "Spin up jVUNDemo site"
  - ps: Start-Job –Name RunIisExpress –Scriptblock {& 'C:\Program Files (x86)\IIS Express\iisexpress.exe' /path:$jVUNDemo /port:57612}
  - ps: Wait-Job -Name RunIisExpress -Timeout 15
  - ps: write-host "Create static version of demo site here: $staticSite"
  - ps: cd $staticSite
  - ps: wget.exe --recursive --convert-links -E --directory-prefix=static-site --no-host-directories http://localhost:57612/
  - ps: write-host "Shut down jVUNDemo site"
  - ps: Get-Job –Name RunIisExpress | Stop-Job
  - ps: Get-Job –Name RunIisExpress | Remove-Job
  - ps: ls $staticSite
