#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - ps: git config --global user.email "johnny_reilly@hotmail.com"
  - ps: git config --global user.name "johnnyreilly"

# environment variables
environment:
  GithubUsername: johnnyreilly
  GithubPassword:
    secure: ilM6UXjXXOmFLz6pDWsoOA==

branches:
  only:
    - master

install:
- ps: choco install wget

build:
  verbosity: minimal

# 'https://$($env:GithubUsername):$($env:GithubPassword)@github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native.git'

after_test:
- ps: git remote -v
- ps: ./makeStatic.ps1 $env:APPVEYOR_BUILD_FOLDER
#- ps: git checkout gh-pages
- ps: git status
#- ps: ls
#- ps: git remote set-url origin 'https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native.git'
#- ps: git remote -v
#- ps: Get-ChildItem -Attributes !r | Remove-Item -Recurse -Force
#- ps: copy-item -path ..\static-site\* -Destination $env:APPVEYOR_BUILD_FOLDER -Recurse
#- ps: git commit -a -m "skip ci - static site regeneration"

